import { useMemo } from 'react'
import type { Analysis } from '../types/analysis'

/** Thrown when window.__MRI_DATA__ is absent. */
export class MriDataMissingError extends Error {
  constructor() {
    super(
      'window.__MRI_DATA__ is not defined. ' +
        'This file must be generated by `repo-mri analyze`, not opened standalone from the ui/ build directory.',
    )
    this.name = 'MriDataMissingError'
  }
}

/** Thrown when window.__MRI_DATA__ exists but is not a valid object. */
export class MriDataInvalidError extends Error {
  constructor(cause: unknown) {
    super(`window.__MRI_DATA__ is not a valid Analysis object: ${String(cause)}`)
    this.name = 'MriDataInvalidError'
  }
}

type MriWindow = Window & { __MRI_DATA__?: unknown }

/**
 * Reads and validates window.__MRI_DATA__.
 * Throws MriDataMissingError if absent; MriDataInvalidError if not an object.
 * Exported for direct testing.
 */
export function loadAnalysis(): Analysis {
  const raw = (window as MriWindow).__MRI_DATA__
  if (raw === undefined) {
    throw new MriDataMissingError()
  }
  if (raw === null || typeof raw !== 'object') {
    throw new MriDataInvalidError(`expected object, got ${typeof raw}`)
  }
  return raw as Analysis
}

/**
 * Returns the parsed Analysis from window.__MRI_DATA__.
 * Throws MriDataMissingError or MriDataInvalidError if the data is absent or malformed.
 * The data is read once and memoised — it never changes at runtime.
 */
export function useAnalysis(): Analysis {
  return useMemo(() => loadAnalysis(), [])
}
